### ISSUE TITLE
Would you be inclined to add support for just nicer remapping ?

### ISSUE THREAD

**Issue by pierrelgol** [fwosar/move-to-next-screen#1]
I read your readme and I figured I might as well ask who knows :)

**Comment by fwosar** [comment]
Sure. Will see if I can add it :)

**Comment by normanr** [comment]
Any chance it can be added to the standard Keyboard Shortcuts dialog?

**Comment by normanr** [comment]
Also it would be nice to document _how_ to change it manually. I failed trying to use dconf, and ended up using gsettings:
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/move-to-next-screen@wosar.me/schemas set org.gnome.shell.extensions.move-to-next-screen move-window-to-next-screen-shortcut "'<Control>grave'"
```

**Comment by fwosar** [comment]
> Any chance it can be added to the standard Keyboard Shortcuts dialog?

Unfortunately not. That was my first hope as well, but it appears like you can only add custom commands to the default shortcut menu. At least, I haven't found any documentation or examples to show otherwise. 

I will not get around adding a custom settings menu to implement shortcut customization, just like all the other extensions I looked at do.

**Comment by fwosar** [comment]
This has been implemented in version 4 now. Enjoy. :)
